# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(950, 560)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(950, 560))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("icons/main_window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame_img_enhance = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_img_enhance.sizePolicy().hasHeightForWidth()
        )
        self.frame_img_enhance.setSizePolicy(sizePolicy)
        self.frame_img_enhance.setMinimumSize(QtCore.QSize(394, 35))
        self.frame_img_enhance.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_img_enhance.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_img_enhance.setObjectName("frame_img_enhance")
        self.layoutWidget = QtWidgets.QWidget(self.frame_img_enhance)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 248, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hLayout_enhance = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.hLayout_enhance.setContentsMargins(0, 0, 0, 0)
        self.hLayout_enhance.setObjectName("hLayout_enhance")
        self.Enhance_btn = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Enhance_btn.sizePolicy().hasHeightForWidth())
        self.Enhance_btn.setSizePolicy(sizePolicy)
        self.Enhance_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("icons/enhanc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Enhance_btn.setIcon(icon1)
        self.Enhance_btn.setIconSize(QtCore.QSize(30, 30))
        self.Enhance_btn.setObjectName("Enhance_btn")
        self.hLayout_enhance.addWidget(self.Enhance_btn)
        self.Equalize_btn = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Equalize_btn.sizePolicy().hasHeightForWidth())
        self.Equalize_btn.setSizePolicy(sizePolicy)
        self.Equalize_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("icons/equalize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Equalize_btn.setIcon(icon2)
        self.Equalize_btn.setIconSize(QtCore.QSize(30, 30))
        self.Equalize_btn.setObjectName("Equalize_btn")
        self.hLayout_enhance.addWidget(self.Equalize_btn)
        self.Gray_btn = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gray_btn.sizePolicy().hasHeightForWidth())
        self.Gray_btn.setSizePolicy(sizePolicy)
        self.Gray_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap("icons/gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Gray_btn.setIcon(icon3)
        self.Gray_btn.setIconSize(QtCore.QSize(30, 30))
        self.Gray_btn.setObjectName("Gray_btn")
        self.hLayout_enhance.addWidget(self.Gray_btn)
        self.Black_white_btn = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Black_white_btn.sizePolicy().hasHeightForWidth()
        )
        self.Black_white_btn.setSizePolicy(sizePolicy)
        self.Black_white_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap("icons/black_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Black_white_btn.setIcon(icon4)
        self.Black_white_btn.setIconSize(QtCore.QSize(30, 30))
        self.Black_white_btn.setObjectName("Black_white_btn")
        self.hLayout_enhance.addWidget(self.Black_white_btn)
        self.White_black_btn = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.White_black_btn.sizePolicy().hasHeightForWidth()
        )
        self.White_black_btn.setSizePolicy(sizePolicy)
        self.White_black_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap("icons/white_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.White_black_btn.setIcon(icon5)
        self.White_black_btn.setIconSize(QtCore.QSize(30, 30))
        self.White_black_btn.setObjectName("White_black_btn")
        self.hLayout_enhance.addWidget(self.White_black_btn)
        self.Undo_btn = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Undo_btn.sizePolicy().hasHeightForWidth())
        self.Undo_btn.setSizePolicy(sizePolicy)
        self.Undo_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap("icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Undo_btn.setIcon(icon6)
        self.Undo_btn.setIconSize(QtCore.QSize(30, 30))
        self.Undo_btn.setObjectName("Undo_btn")
        self.hLayout_enhance.addWidget(self.Undo_btn)
        self.Label_btn = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_btn.sizePolicy().hasHeightForWidth())
        self.Label_btn.setSizePolicy(sizePolicy)
        self.Label_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap("icons/label.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Label_btn.setIcon(icon7)
        self.Label_btn.setIconSize(QtCore.QSize(30, 30))
        self.Label_btn.setObjectName("Label_btn")
        self.hLayout_enhance.addWidget(self.Label_btn)
        self.gridLayout.addWidget(self.frame_img_enhance, 2, 0, 1, 1)
        self.hLayout_expl = QtWidgets.QHBoxLayout()
        self.hLayout_expl.setObjectName("hLayout_expl")
        self.Previous_file_btn = QtWidgets.QToolButton(self.centralwidget)
        self.Previous_file_btn.setEnabled(False)
        self.Previous_file_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap("icons/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Previous_file_btn.setIcon(icon8)
        self.Previous_file_btn.setIconSize(QtCore.QSize(30, 30))
        self.Previous_file_btn.setObjectName("Previous_file_btn")
        self.hLayout_expl.addWidget(self.Previous_file_btn)
        self.File_name = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.File_name.sizePolicy().hasHeightForWidth())
        self.File_name.setSizePolicy(sizePolicy)
        self.File_name.setMinimumSize(QtCore.QSize(0, 25))
        self.File_name.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.File_name.setObjectName("File_name")
        self.hLayout_expl.addWidget(self.File_name)
        self.Next_file_btn = QtWidgets.QToolButton(self.centralwidget)
        self.Next_file_btn.setEnabled(False)
        self.Next_file_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(
            QtGui.QPixmap("icons/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Next_file_btn.setIcon(icon9)
        self.Next_file_btn.setIconSize(QtCore.QSize(30, 30))
        self.Next_file_btn.setArrowType(QtCore.Qt.NoArrow)
        self.Next_file_btn.setObjectName("Next_file_btn")
        self.hLayout_expl.addWidget(self.Next_file_btn)
        self.gridLayout.addLayout(self.hLayout_expl, 0, 0, 1, 1)
        self.frame_roi_opt = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_roi_opt.sizePolicy().hasHeightForWidth()
        )
        self.frame_roi_opt.setSizePolicy(sizePolicy)
        self.frame_roi_opt.setMinimumSize(QtCore.QSize(35, 295))
        self.frame_roi_opt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_roi_opt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_roi_opt.setObjectName("frame_roi_opt")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_roi_opt)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 32, 284))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.vLayout_roi_opt = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.vLayout_roi_opt.setContentsMargins(0, 0, 0, 0)
        self.vLayout_roi_opt.setObjectName("vLayout_roi_opt")
        self.single_ROI_btn = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.single_ROI_btn.sizePolicy().hasHeightForWidth()
        )
        self.single_ROI_btn.setSizePolicy(sizePolicy)
        self.single_ROI_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(
            QtGui.QPixmap("icons/ROI1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.single_ROI_btn.setIcon(icon10)
        self.single_ROI_btn.setIconSize(QtCore.QSize(30, 30))
        self.single_ROI_btn.setObjectName("single_ROI_btn")
        self.vLayout_roi_opt.addWidget(self.single_ROI_btn)
        self.edge_ROI_btn = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edge_ROI_btn.sizePolicy().hasHeightForWidth())
        self.edge_ROI_btn.setSizePolicy(sizePolicy)
        self.edge_ROI_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(
            QtGui.QPixmap("icons/ROI2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.edge_ROI_btn.setIcon(icon11)
        self.edge_ROI_btn.setIconSize(QtCore.QSize(30, 30))
        self.edge_ROI_btn.setObjectName("edge_ROI_btn")
        self.vLayout_roi_opt.addWidget(self.edge_ROI_btn)
        self.multiple_ROI_btn = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.multiple_ROI_btn.sizePolicy().hasHeightForWidth()
        )
        self.multiple_ROI_btn.setSizePolicy(sizePolicy)
        self.multiple_ROI_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(
            QtGui.QPixmap("icons/ROI4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.multiple_ROI_btn.setIcon(icon12)
        self.multiple_ROI_btn.setIconSize(QtCore.QSize(30, 30))
        self.multiple_ROI_btn.setObjectName("multiple_ROI_btn")
        self.vLayout_roi_opt.addWidget(self.multiple_ROI_btn)
        self.Undo_ROI_actions = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Undo_ROI_actions.sizePolicy().hasHeightForWidth()
        )
        self.Undo_ROI_actions.setSizePolicy(sizePolicy)
        self.Undo_ROI_actions.setMinimumSize(QtCore.QSize(30, 30))
        self.Undo_ROI_actions.setIcon(icon6)
        self.Undo_ROI_actions.setIconSize(QtCore.QSize(30, 30))
        self.Undo_ROI_actions.setObjectName("Undo_ROI_actions")
        self.vLayout_roi_opt.addWidget(self.Undo_ROI_actions)
        self.ROI_color = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_color.sizePolicy().hasHeightForWidth())
        self.ROI_color.setSizePolicy(sizePolicy)
        self.ROI_color.setMinimumSize(QtCore.QSize(30, 30))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(
            QtGui.QPixmap("icons/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.ROI_color.setIcon(icon13)
        self.ROI_color.setIconSize(QtCore.QSize(30, 30))
        self.ROI_color.setObjectName("ROI_color")
        self.vLayout_roi_opt.addWidget(self.ROI_color)
        self.ROI_width_up = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_width_up.sizePolicy().hasHeightForWidth())
        self.ROI_width_up.setSizePolicy(sizePolicy)
        self.ROI_width_up.setMinimumSize(QtCore.QSize(30, 30))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(
            QtGui.QPixmap("icons/ROI_w+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.ROI_width_up.setIcon(icon14)
        self.ROI_width_up.setIconSize(QtCore.QSize(30, 30))
        self.ROI_width_up.setObjectName("ROI_width_up")
        self.vLayout_roi_opt.addWidget(self.ROI_width_up)
        self.ROI_width_down = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ROI_width_down.sizePolicy().hasHeightForWidth()
        )
        self.ROI_width_down.setSizePolicy(sizePolicy)
        self.ROI_width_down.setMinimumSize(QtCore.QSize(30, 30))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(
            QtGui.QPixmap("icons/ROI_w-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.ROI_width_down.setIcon(icon15)
        self.ROI_width_down.setIconSize(QtCore.QSize(30, 30))
        self.ROI_width_down.setObjectName("ROI_width_down")
        self.vLayout_roi_opt.addWidget(self.ROI_width_down)
        self.image_ROI_btn = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.image_ROI_btn.sizePolicy().hasHeightForWidth()
        )
        self.image_ROI_btn.setSizePolicy(sizePolicy)
        self.image_ROI_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(
            QtGui.QPixmap("icons/ROI3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.image_ROI_btn.setIcon(icon16)
        self.image_ROI_btn.setIconSize(QtCore.QSize(30, 30))
        self.image_ROI_btn.setObjectName("image_ROI_btn")
        self.vLayout_roi_opt.addWidget(self.image_ROI_btn)
        self.gridLayout.addWidget(self.frame_roi_opt, 1, 1, 1, 1)
        self.frame_left_dynamic = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_left_dynamic.sizePolicy().hasHeightForWidth()
        )
        self.frame_left_dynamic.setSizePolicy(sizePolicy)
        self.frame_left_dynamic.setMinimumSize(QtCore.QSize(394, 35))
        self.frame_left_dynamic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_dynamic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_dynamic.setObjectName("frame_left_dynamic")

        Ui_MainWindow.layoutWidget_3 = QtWidgets.QWidget(self.frame_left_dynamic)

        self.gridLayout.addWidget(self.frame_left_dynamic, 3, 0, 1, 1)
        self.Source_File = QLabelplus(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Source_File.sizePolicy().hasHeightForWidth())
        self.Source_File.setSizePolicy(sizePolicy)
        self.Source_File.setMinimumSize(QtCore.QSize(394, 298))
        self.Source_File.setFrameShape(QtWidgets.QFrame.Box)
        self.Source_File.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Source_File.setText("")
        self.Source_File.setScaledContents(True)
        self.Source_File.setAlignment(QtCore.Qt.AlignCenter)
        self.Source_File.setObjectName("Source_File")
        self.gridLayout.addWidget(self.Source_File, 1, 0, 1, 1)
        self.left_label_indicator = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.left_label_indicator.sizePolicy().hasHeightForWidth()
        )
        self.left_label_indicator.setSizePolicy(sizePolicy)
        self.left_label_indicator.setMinimumSize(QtCore.QSize(30, 30))
        self.left_label_indicator.setMaximumSize(QtCore.QSize(30, 30))
        self.left_label_indicator.setText("")
        self.left_label_indicator.setScaledContents(True)
        self.left_label_indicator.setObjectName("left_label_indicator")
        self.gridLayout.addWidget(self.left_label_indicator, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.Dir_name = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dir_name.sizePolicy().hasHeightForWidth())
        self.Dir_name.setSizePolicy(sizePolicy)
        self.Dir_name.setMinimumSize(QtCore.QSize(425, 30))
        self.Dir_name.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.Dir_name.setObjectName("Dir_name")
        self.gridLayout_3.addWidget(self.Dir_name, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_roi_up = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_roi_up.sizePolicy().hasHeightForWidth())
        self.frame_roi_up.setSizePolicy(sizePolicy)
        self.frame_roi_up.setMinimumSize(QtCore.QSize(394, 35))
        self.frame_roi_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_roi_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_roi_up.setObjectName("frame_roi_up")
        self.gridLayout_2.addWidget(self.frame_roi_up, 0, 0, 1, 1)
        self.frame_roi_right = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_roi_right.sizePolicy().hasHeightForWidth()
        )
        self.frame_roi_right.setSizePolicy(sizePolicy)
        self.frame_roi_right.setMinimumSize(QtCore.QSize(35, 295))
        self.frame_roi_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_roi_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_roi_right.setObjectName("frame_roi_right")
        self.gridLayout_2.addWidget(self.frame_roi_right, 1, 1, 1, 1)
        self.frame_right_dynamic = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_right_dynamic.sizePolicy().hasHeightForWidth()
        )
        self.frame_right_dynamic.setSizePolicy(sizePolicy)
        self.frame_right_dynamic.setMinimumSize(QtCore.QSize(394, 35))
        self.frame_right_dynamic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right_dynamic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right_dynamic.setObjectName("frame_right_dynamic")

        Ui_MainWindow.layoutWidget_4 = QtWidgets.QWidget(self.frame_right_dynamic)

        self.gridLayout_2.addWidget(self.frame_right_dynamic, 3, 0, 1, 1)
        self.frame_roi_tools = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_roi_tools.sizePolicy().hasHeightForWidth()
        )
        self.frame_roi_tools.setSizePolicy(sizePolicy)
        self.frame_roi_tools.setMinimumSize(QtCore.QSize(394, 35))
        self.frame_roi_tools.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_roi_tools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_roi_tools.setObjectName("frame_roi_tools")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_roi_tools)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 284, 32))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.hLayout_roi_tools = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.hLayout_roi_tools.setContentsMargins(0, 0, 0, 0)
        self.hLayout_roi_tools.setObjectName("hLayout_roi_tools")
        self.Edge_manual = QtWidgets.QToolButton(self.layoutWidget_2)
        self.Edge_manual.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edge_manual.sizePolicy().hasHeightForWidth())
        self.Edge_manual.setSizePolicy(sizePolicy)
        self.Edge_manual.setMinimumSize(QtCore.QSize(30, 30))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(
            QtGui.QPixmap("icons/paint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Edge_manual.setIcon(icon17)
        self.Edge_manual.setIconSize(QtCore.QSize(30, 30))
        self.Edge_manual.setObjectName("Edge_manual")
        self.hLayout_roi_tools.addWidget(self.Edge_manual)
        self.Edge_detection = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Edge_detection.sizePolicy().hasHeightForWidth()
        )
        self.Edge_detection.setSizePolicy(sizePolicy)
        self.Edge_detection.setMinimumSize(QtCore.QSize(30, 30))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(
            QtGui.QPixmap("icons/edge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Edge_detection.setIcon(icon18)
        self.Edge_detection.setIconSize(QtCore.QSize(30, 30))
        self.Edge_detection.setObjectName("Edge_detection")
        self.hLayout_roi_tools.addWidget(self.Edge_detection)
        self.Edge_gray_btn = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Edge_gray_btn.sizePolicy().hasHeightForWidth()
        )
        self.Edge_gray_btn.setSizePolicy(sizePolicy)
        self.Edge_gray_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.Edge_gray_btn.setIcon(icon3)
        self.Edge_gray_btn.setIconSize(QtCore.QSize(30, 30))
        self.Edge_gray_btn.setObjectName("Edge_gray_btn")
        self.hLayout_roi_tools.addWidget(self.Edge_gray_btn)
        self.Edge_black_white_btn = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Edge_black_white_btn.sizePolicy().hasHeightForWidth()
        )
        self.Edge_black_white_btn.setSizePolicy(sizePolicy)
        self.Edge_black_white_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.Edge_black_white_btn.setIcon(icon4)
        self.Edge_black_white_btn.setIconSize(QtCore.QSize(30, 30))
        self.Edge_black_white_btn.setObjectName("Edge_black_white_btn")
        self.hLayout_roi_tools.addWidget(self.Edge_black_white_btn)
        self.Edge_white_black_btn = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Edge_white_black_btn.sizePolicy().hasHeightForWidth()
        )
        self.Edge_white_black_btn.setSizePolicy(sizePolicy)
        self.Edge_white_black_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.Edge_white_black_btn.setIcon(icon5)
        self.Edge_white_black_btn.setIconSize(QtCore.QSize(30, 30))
        self.Edge_white_black_btn.setObjectName("Edge_white_black_btn")
        self.hLayout_roi_tools.addWidget(self.Edge_white_black_btn)
        self.Undo_btn_edge = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Undo_btn_edge.sizePolicy().hasHeightForWidth()
        )
        self.Undo_btn_edge.setSizePolicy(sizePolicy)
        self.Undo_btn_edge.setMinimumSize(QtCore.QSize(30, 30))
        self.Undo_btn_edge.setIcon(icon6)
        self.Undo_btn_edge.setIconSize(QtCore.QSize(30, 30))
        self.Undo_btn_edge.setObjectName("Undo_btn_edge")
        self.hLayout_roi_tools.addWidget(self.Undo_btn_edge)
        self.Mask_btn = QtWidgets.QToolButton(self.layoutWidget_2)
        self.Mask_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mask_btn.sizePolicy().hasHeightForWidth())
        self.Mask_btn.setSizePolicy(sizePolicy)
        self.Mask_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(
            QtGui.QPixmap("icons/mask.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Mask_btn.setIcon(icon19)
        self.Mask_btn.setIconSize(QtCore.QSize(30, 30))
        self.Mask_btn.setObjectName("Mask_btn")
        self.hLayout_roi_tools.addWidget(self.Mask_btn)
        self.Save_mask_btn = QtWidgets.QToolButton(self.layoutWidget_2)
        self.Save_mask_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Save_mask_btn.sizePolicy().hasHeightForWidth()
        )
        self.Save_mask_btn.setSizePolicy(sizePolicy)
        self.Save_mask_btn.setMinimumSize(QtCore.QSize(30, 30))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(
            QtGui.QPixmap("icons/save_mask.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.Save_mask_btn.setIcon(icon20)
        self.Save_mask_btn.setIconSize(QtCore.QSize(30, 30))
        self.Save_mask_btn.setObjectName("Save_mask_btn")
        self.hLayout_roi_tools.addWidget(self.Save_mask_btn)
        self.gridLayout_2.addWidget(self.frame_roi_tools, 2, 0, 1, 1)
        self.Work_Area = QLabelplusplus(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Work_Area.sizePolicy().hasHeightForWidth())
        self.Work_Area.setSizePolicy(sizePolicy)
        self.Work_Area.setMinimumSize(QtCore.QSize(394, 298))
        self.Work_Area.setFrameShape(QtWidgets.QFrame.Box)
        self.Work_Area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Work_Area.setText("")
        self.Work_Area.setScaledContents(True)
        self.Work_Area.setAlignment(QtCore.Qt.AlignCenter)
        self.Work_Area.setObjectName("Work_Area")
        self.gridLayout_2.addWidget(self.Work_Area, 1, 0, 1, 1)
        self.right_label_indicator = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.right_label_indicator.sizePolicy().hasHeightForWidth()
        )
        self.right_label_indicator.setSizePolicy(sizePolicy)
        self.right_label_indicator.setMinimumSize(QtCore.QSize(30, 30))
        self.right_label_indicator.setMaximumSize(QtCore.QSize(30, 30))
        self.right_label_indicator.setText("")
        self.right_label_indicator.setScaledContents(True)
        self.right_label_indicator.setObjectName("right_label_indicator")
        self.gridLayout_2.addWidget(self.right_label_indicator, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 23))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuRealce = QtWidgets.QMenu(self.menubar)
        self.menuRealce.setObjectName("menuRealce")
        self.menuAnotar_imagen = QtWidgets.QMenu(self.menubar)
        self.menuAnotar_imagen.setObjectName("menuAnotar_imagen")
        self.menuROI = QtWidgets.QMenu(self.menubar)
        self.menuROI.setObjectName("menuROI")
        self.menuROI_2 = QtWidgets.QMenu(self.menubar)
        self.menuROI_2.setObjectName("menuROI_2")
        self.menuCrear_mascara = QtWidgets.QMenu(self.menubar)
        self.menuCrear_mascara.setObjectName("menuCrear_mascara")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMinimumSize(QtCore.QSize(425, 34))
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Open_file = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(
            QtGui.QPixmap("icons/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.action_Open_file.setIcon(icon21)
        self.action_Open_file.setObjectName("action_Open_file")
        self.action_Open_folder = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(
            QtGui.QPixmap("icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.action_Open_folder.setIcon(icon22)
        self.action_Open_folder.setObjectName("action_Open_folder")
        self.action_Enhance_buttons = QtWidgets.QAction(MainWindow)
        self.action_Enhance_buttons.setIcon(icon1)
        self.action_Enhance_buttons.setObjectName("action_Enhance_buttons")
        self.action_Enhance_sliders = QtWidgets.QAction(MainWindow)
        self.action_Enhance_sliders.setIcon(icon2)
        self.action_Enhance_sliders.setObjectName("action_Enhance_sliders")
        self.action_Convertir_escala_grises = QtWidgets.QAction(MainWindow)
        self.action_Convertir_escala_grises.setIcon(icon3)
        self.action_Convertir_escala_grises.setObjectName(
            "action_Convertir_escala_grises"
        )
        self.action_Imagen_binaria = QtWidgets.QAction(MainWindow)
        self.action_Imagen_binaria.setIcon(icon4)
        self.action_Imagen_binaria.setObjectName("action_Imagen_binaria")
        self.action_Imagen_binaria_invertida = QtWidgets.QAction(MainWindow)
        self.action_Imagen_binaria_invertida.setIcon(icon5)
        self.action_Imagen_binaria_invertida.setObjectName(
            "action_Imagen_binaria_invertida"
        )
        self.action_Deshacer_imagen = QtWidgets.QAction(MainWindow)
        self.action_Deshacer_imagen.setIcon(icon6)
        self.action_Deshacer_imagen.setObjectName("action_Deshacer_imagen")
        self.action_Crear_imagen_etiquetada = QtWidgets.QAction(MainWindow)
        self.action_Crear_imagen_etiquetada.setIcon(icon7)
        self.action_Crear_imagen_etiquetada.setObjectName(
            "action_Crear_imagen_etiquetada"
        )
        self.action_ROI_simple = QtWidgets.QAction(MainWindow)
        self.action_ROI_simple.setIcon(icon10)
        self.action_ROI_simple.setObjectName("action_ROI_simple")
        self.action_ROI_contornos = QtWidgets.QAction(MainWindow)
        self.action_ROI_contornos.setIcon(icon11)
        self.action_ROI_contornos.setObjectName("action_ROI_contornos")
        self.action_ROI_multiple = QtWidgets.QAction(MainWindow)
        self.action_ROI_multiple.setIcon(icon12)
        self.action_ROI_multiple.setObjectName("action_ROI_multiple")
        self.action_Deshacer_ROI = QtWidgets.QAction(MainWindow)
        self.action_Deshacer_ROI.setIcon(icon6)
        self.action_Deshacer_ROI.setObjectName("action_Deshacer_ROI")
        self.action_Seleccionar_color = QtWidgets.QAction(MainWindow)
        self.action_Seleccionar_color.setIcon(icon13)
        self.action_Seleccionar_color.setObjectName("action_Seleccionar_color")
        self.action_Aumentar_trazo = QtWidgets.QAction(MainWindow)
        self.action_Aumentar_trazo.setIcon(icon14)
        self.action_Aumentar_trazo.setObjectName("action_Aumentar_trazo")
        self.action_Disminuir_trazo = QtWidgets.QAction(MainWindow)
        self.action_Disminuir_trazo.setIcon(icon15)
        self.action_Disminuir_trazo.setObjectName("action_Disminuir_trazo")
        self.action_Herramientas_pintura = QtWidgets.QAction(MainWindow)
        self.action_Herramientas_pintura.setIcon(icon17)
        self.action_Herramientas_pintura.setObjectName("action_Herramientas_pintura")
        self.action_Deteccion_bordes = QtWidgets.QAction(MainWindow)
        self.action_Deteccion_bordes.setIcon(icon18)
        self.action_Deteccion_bordes.setObjectName("action_Deteccion_bordes")
        self.action_ROI_escala_grises = QtWidgets.QAction(MainWindow)
        self.action_ROI_escala_grises.setIcon(icon3)
        self.action_ROI_escala_grises.setObjectName("action_ROI_escala_grises")
        self.action_ROI_binario = QtWidgets.QAction(MainWindow)
        self.action_ROI_binario.setIcon(icon4)
        self.action_ROI_binario.setObjectName("action_ROI_binario")
        self.action_ROI_binario_invertido = QtWidgets.QAction(MainWindow)
        self.action_ROI_binario_invertido.setIcon(icon5)
        self.action_ROI_binario_invertido.setObjectName("action_ROI_binario_invertido")
        self.action_Deshacer_area = QtWidgets.QAction(MainWindow)
        self.action_Deshacer_area.setIcon(icon6)
        self.action_Deshacer_area.setObjectName("action_Deshacer_area")
        self.action_Ver_mascara = QtWidgets.QAction(MainWindow)
        self.action_Ver_mascara.setIcon(icon19)
        self.action_Ver_mascara.setObjectName("action_Ver_mascara")
        self.action_Salvar_mascara = QtWidgets.QAction(MainWindow)
        self.action_Salvar_mascara.setIcon(icon20)
        self.action_Salvar_mascara.setObjectName("action_Salvar_mascara")
        self.menuArchivo.addAction(self.action_Open_file)
        self.menuArchivo.addAction(self.action_Open_folder)
        self.menuRealce.addAction(self.action_Enhance_buttons)
        self.menuRealce.addAction(self.action_Enhance_sliders)
        self.menuRealce.addAction(self.action_Convertir_escala_grises)
        self.menuRealce.addAction(self.action_Imagen_binaria)
        self.menuRealce.addAction(self.action_Imagen_binaria_invertida)
        self.menuRealce.addAction(self.action_Deshacer_imagen)
        self.menuAnotar_imagen.addAction(self.action_Crear_imagen_etiquetada)
        self.menuROI.addAction(self.action_ROI_simple)
        self.menuROI.addAction(self.action_ROI_contornos)
        self.menuROI.addAction(self.action_ROI_multiple)
        self.menuROI.addAction(self.action_Deshacer_ROI)
        self.menuROI.addAction(self.action_Seleccionar_color)
        self.menuROI.addAction(self.action_Aumentar_trazo)
        self.menuROI.addAction(self.action_Disminuir_trazo)
        self.menuROI_2.addAction(self.action_Herramientas_pintura)
        self.menuROI_2.addAction(self.action_Deteccion_bordes)
        self.menuROI_2.addAction(self.action_ROI_escala_grises)
        self.menuROI_2.addAction(self.action_ROI_binario)
        self.menuROI_2.addAction(self.action_ROI_binario_invertido)
        self.menuROI_2.addAction(self.action_Deshacer_area)
        self.menuCrear_mascara.addAction(self.action_Ver_mascara)
        self.menuCrear_mascara.addAction(self.action_Salvar_mascara)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuRealce.menuAction())
        self.menubar.addAction(self.menuROI.menuAction())
        self.menubar.addAction(self.menuAnotar_imagen.menuAction())
        self.menubar.addAction(self.menuROI_2.menuAction())
        self.menubar.addAction(self.menuCrear_mascara.menuAction())
        self.toolBar.addAction(self.action_Open_file)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Open_folder)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Anotador"))
        self.Enhance_btn.setText(_translate("MainWindow", "..."))
        self.Equalize_btn.setText(_translate("MainWindow", "..."))
        self.Gray_btn.setText(_translate("MainWindow", "..."))
        self.Black_white_btn.setText(_translate("MainWindow", "..."))
        self.White_black_btn.setText(_translate("MainWindow", "..."))
        self.Undo_btn.setText(_translate("MainWindow", "..."))
        self.Label_btn.setText(_translate("MainWindow", "..."))
        self.Previous_file_btn.setText(_translate("MainWindow", "..."))
        self.File_name.setText(_translate("MainWindow", "Nombre del fichero"))
        self.Next_file_btn.setText(_translate("MainWindow", "..."))
        self.single_ROI_btn.setText(_translate("MainWindow", "..."))
        self.edge_ROI_btn.setText(_translate("MainWindow", "..."))
        self.multiple_ROI_btn.setText(_translate("MainWindow", "..."))
        self.Undo_ROI_actions.setText(_translate("MainWindow", "..."))
        self.ROI_color.setText(_translate("MainWindow", "..."))
        self.ROI_width_up.setText(_translate("MainWindow", "..."))
        self.ROI_width_down.setText(_translate("MainWindow", "..."))
        self.image_ROI_btn.setText(_translate("MainWindow", "..."))
        self.Dir_name.setText(_translate("MainWindow", "Directorio"))
        self.Edge_manual.setText(_translate("MainWindow", "..."))
        self.Edge_detection.setText(_translate("MainWindow", "..."))
        self.Edge_gray_btn.setText(_translate("MainWindow", "..."))
        self.Edge_black_white_btn.setText(_translate("MainWindow", "..."))
        self.Edge_white_black_btn.setText(_translate("MainWindow", "..."))
        self.Undo_btn_edge.setText(_translate("MainWindow", "..."))
        self.Mask_btn.setText(_translate("MainWindow", "..."))
        self.Save_mask_btn.setText(_translate("MainWindow", "..."))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuRealce.setTitle(_translate("MainWindow", "Operaciones"))
        self.menuAnotar_imagen.setTitle(_translate("MainWindow", "Etiquetar imagen"))
        self.menuROI.setTitle(_translate("MainWindow", "ROI opciones"))
        self.menuROI_2.setTitle(_translate("MainWindow", "ROI"))
        self.menuCrear_mascara.setTitle(_translate("MainWindow", "Crear mascara"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_Open_file.setText(_translate("MainWindow", "Abrir fichero"))
        self.action_Open_folder.setText(
            _translate("MainWindow", "Abrir carpeta directorio")
        )
        self.action_Enhance_buttons.setText(_translate("MainWindow", "Realce"))
        self.action_Enhance_sliders.setText(_translate("MainWindow", "Equalizar"))
        self.action_Convertir_escala_grises.setText(
            _translate("MainWindow", "Imagen en escala de grises")
        )
        self.action_Imagen_binaria.setText(_translate("MainWindow", "Imagen binaria"))
        self.action_Imagen_binaria_invertida.setText(
            _translate("MainWindow", "Imagen binaria invertida")
        )
        self.action_Deshacer_imagen.setText(_translate("MainWindow", "Deshacer"))
        self.action_Crear_imagen_etiquetada.setText(
            _translate("MainWindow", "Crear imagen etiquetada")
        )
        self.action_ROI_simple.setText(_translate("MainWindow", "ROI simple"))
        self.action_ROI_contornos.setText(_translate("MainWindow", "ROI contornos"))
        self.action_ROI_multiple.setText(_translate("MainWindow", "ROI multiple"))
        self.action_Deshacer_ROI.setText(_translate("MainWindow", "Deshacer"))
        self.action_Seleccionar_color.setText(
            _translate("MainWindow", "Seleccionar color")
        )
        self.action_Aumentar_trazo.setText(_translate("MainWindow", "Aumentar trazo"))
        self.action_Disminuir_trazo.setText(_translate("MainWindow", "Disminuir trazo"))
        self.action_Herramientas_pintura.setText(
            _translate("MainWindow", "Herramientas de pintura")
        )
        self.action_Deteccion_bordes.setText(
            _translate("MainWindow", "Detección de bordes")
        )
        self.action_ROI_escala_grises.setText(
            _translate("MainWindow", "ROI escala de grises")
        )
        self.action_ROI_binario.setText(_translate("MainWindow", "ROI binario"))
        self.action_ROI_binario_invertido.setText(
            _translate("MainWindow", "ROI binario invertido")
        )
        self.action_Deshacer_area.setText(_translate("MainWindow", "Deshacer"))
        self.action_Ver_mascara.setText(_translate("MainWindow", "Ver mascara"))
        self.action_Salvar_mascara.setText(_translate("MainWindow", "Salvar mascara"))


from QLabelSourceplus import QLabelplus
from QLabelWorkplus import QLabelplusplus
